micronaut:
  application:
    name: ACME Equipment manager
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      default:
        enabled: true
        mapping: /**
        paths: classpath:public
jackson:
  serializationInclusion: ALWAYS
  serialization:
    writeDatesAsTimestamps: false
    writeDateTimestampsAsNanoseconds: false